
server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb://root:Passw0rd#007@mongodb:27017/bankingSystem?authSource=admin

  kafka:
    producer:
      bootstrap-servers: kafka-broker-1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
