
server:
  port: 5000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankingSystem

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serializatation.StringSerializer
      value-serializer: org.springframework.kafka.support.serailizer.JsonSerializer
