server:
  port: 5001


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/bankingAccount?createDatabaseIfNotExist=true
    username: root
    password: Passw0rd#007
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers:
        - kafka-broker-1:9092
      group-id: bankAccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

logging:
  level:
    ROOT: INFO
